name: bmdriver
description: Server benchmark driver.
version: 1.0.0
#homepage: https://www.example.com
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  http: ^0.11.3
  go: ^1.0.6
  duration: ^1.0.0
  text_table: ^2.5.1

dev_dependencies:
  test: ^0.12.0
